version: "3.8"

services:
  tempo:
    #image: grafana/tempo:latest
    image: grafana/tempo:main-de45a61-arm64
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo_data:/tmp/tempo
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200"  # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
  loki:
    #image: grafana/loki:latest
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  collector:
    #image: otel/opentelemetry-collector-contrib:latest
    image: otel/opentelemetry-collector-contrib:0.74.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8090"
    volumes:
      - ./collector/collector.yaml:/etc/otelcol-contrib/config.yaml
  prometheus:
    #image: prom/prometheus:latest
    image: prom/prometheus:latest
    command:
      - "--enable-feature=remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    #image: grafana/grafana-enterprise
    image: grafana/grafana-enterprise
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/vaadin-dashboard.json:/var/lib/grafana/dashboards/vaadin-dashboard.json
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "tempoApmTable"
    ports:
      - "3000:3000"

volumes:
  prometheus:
    driver: local
  grafana_data:
    driver: local
  tempo_data:
    driver: local
