{
 "title": "Vaadin Dashboard - 4.0.0",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{exported_job=\"vaadin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (Process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{exported_job=\"vaadin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "query": "{}", "limit": 20, "tableType": "traces" }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "query": "{status = error}", "limit": 20, "tableType": "traces" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{service_name=\"vaadin\"} |= ``"
    }
   ]
  }
 ]
}